### ISSUE TITLE
Inline Style

### ISSUE THREAD

**Issue by gaurish-saini** [nbisht11/CC-Elib#2]
Remove in-line style, those can be moved to style.css and can be defined under some class/id.

`temp.php`

**Line number :: 7**

![image](https://user-images.githubusercontent.com/58362095/116356641-2a2a5c00-a819-11eb-95a7-afa157fb8a5c.png)

**Line number :: 27**

![image](https://user-images.githubusercontent.com/58362095/116357109-bb013780-a819-11eb-86b9-ab31e8b7d262.png)

`index.php`

**Line number :: 138**

![image](https://user-images.githubusercontent.com/58362095/116357775-817cfc00-a81a-11eb-942a-9f1ac26137b6.png)

**Line number :: 109,110**

![image](https://user-images.githubusercontent.com/58362095/116358315-239ce400-a81b-11eb-8f63-ed9312edcf5c.png)

**Comment by nbisht11** [comment]
Created classes in style.css and removed the inline css.
