### ISSUE TITLE
Inconsistent indentation

### ISSUE THREAD

**Issue by gaurish-saini** [nbisht11/CC-Elib#4]
Inconsistent indentation is causing confusion for a particular code component.

`index.php`

![image](https://user-images.githubusercontent.com/58362095/116359610-9eb2ca00-a81c-11eb-8ed8-748801f613f2.png)

**Comment by nbisht11** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/68755057/116522429-d2602380-a8f2-11eb-8d67-213b7a5de0af.png)
