### ISSUE TITLE
Style code in style file

### ISSUE THREAD

**Issue by gaurish-saini** [nbisht11/CC-Elib#5]
style code can be moved to `style.css` and it will reduce the effort to load it again and again in different files.

`index.php`

![image](https://user-images.githubusercontent.com/58362095/116360088-2dbfe200-a81d-11eb-9b20-e58382b2f015.png)

`edit_book.php`

![image](https://user-images.githubusercontent.com/58362095/116362318-8c865b00-a81f-11eb-8c52-6b7660fc4d43.png)

**Comment by nbisht11** [comment]
Fixed,
Moved the code to style.css
![Issue#3](https://user-images.githubusercontent.com/68755057/116522905-4d293e80-a8f3-11eb-9de8-9cc2741d1d48.png)
