### ISSUE TITLE
Explanation of `links.php`

### ISSUE THREAD

**Issue by gaurish-saini** [nbisht11/CC-Elib#6]
confusion between how its being loaded in different files, and those files are further included in one another

`index.php`
![image](https://user-images.githubusercontent.com/58362095/116360596-b9d20980-a81d-11eb-8f10-3158af7af4a1.png)

`header.php`
![image](https://user-images.githubusercontent.com/58362095/116360737-d706d800-a81d-11eb-8224-286b2149c287.png)

**Comment by nbisht11** [comment]
This file is no longer in use.
