### ISSUE TITLE
File structure directory

### ISSUE THREAD

**Issue by gaurish-saini** [nbisht11/CC-Elib#7]
Essentials and common files can have a dedicated folder, to define better understandability.

`common | templates | etc.`
![image](https://user-images.githubusercontent.com/58362095/116361219-5eece200-a81e-11eb-8d78-13ab79615fdd.png)

`config` 
![image](https://user-images.githubusercontent.com/58362095/116361501-ad9a7c00-a81e-11eb-8c97-82f874a64acf.png)

**Comment by nbisht11** [comment]
Created file structure 
(https://user-images.githubusercontent.com/68755057/116519785-8495ec00-a8ef-11eb-929b-3e7d08e5eaf7.png)
