### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by gaurish-saini** [nbisht11/CC-Elib#8]
Naming conventions can be self-evident.

-------------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/58362095/116361810-01a56080-a81f-11eb-9740-89e874e5fb31.png)

-------------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/58362095/116361827-09650500-a81f-11eb-9911-d8dea5b04103.png)

**Comment by nbisht11** [comment]
temp.php was a temporary file that mistakenly got committed. And files is a folder that stores two other folders: Book_Covers and images. Book_Covers stores the Book_Cover images and images store the necessary images like background image etc.
